In [1]:
import torch

d:\Anaconda\envs\LLms\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
embedding = torch.nn.Embedding(10, 3)

In [3]:
print(embedding)

Embedding(10, 3)


In [11]:
embedding.num_embeddings
param = [param for param in embedding.parameters()]
print(param)
print(embedding.weight)

[Parameter containing:
tensor([[ 0.9857, -0.4409, -0.5023],
        [-1.1811,  0.1074, -1.7073],
        [-2.1280,  1.3203, -0.3036],
        [-0.3111,  1.2616,  1.0787],
        [ 0.2928,  1.2481, -1.3790],
        [ 1.2427, -0.3067,  2.1434],
        [ 0.2074, -0.9600,  0.3037],
        [ 0.9559, -1.0391,  0.1019],
        [-0.2852, -0.0045,  0.6466],
        [ 0.4619,  0.8868,  0.4484]], requires_grad=True)]
Parameter containing:
tensor([[ 0.9857, -0.4409, -0.5023],
        [-1.1811,  0.1074, -1.7073],
        [-2.1280,  1.3203, -0.3036],
        [-0.3111,  1.2616,  1.0787],
        [ 0.2928,  1.2481, -1.3790],
        [ 1.2427, -0.3067,  2.1434],
        [ 0.2074, -0.9600,  0.3037],
        [ 0.9559, -1.0391,  0.1019],
        [-0.2852, -0.0045,  0.6466],
        [ 0.4619,  0.8868,  0.4484]], requires_grad=True)


In [7]:
input_torch = torch.LongTensor([1,2,3,4])
embeding_result = embedding(input_torch)
print(embeding_result.shape)
print(embeding_result)

tensor([[-1.1811,  0.1074, -1.7073],
        [-2.1280,  1.3203, -0.3036],
        [-0.3111,  1.2616,  1.0787],
        [ 0.2928,  1.2481, -1.3790]], grad_fn=<EmbeddingBackward0>)

In [14]:
result = torch.matmul(input_torch, embedding.weight)
result

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x4 and 10x3)